- src/button/button.style.ts
> feat(bo): add user tokens to button styles

- src/button/button.stories.ts
> feat: add story for button component

- src/radio-group/index.ts
- src/radio-group/radio-group.stories.ts
- src/radio-group/radio-group.style.ts
- src/radio-group/radio-group.ts
- src/radio/radio.style.ts
- src/radio/radio.ts
close: https://github.com/Tap30/web-components/issues/56
> feat: add-radio-group-component

- src/banner/banner.stories.ts
- src/banner/banner.style.ts
- src/banner/banner.ts
- src/banner/index.ts
- src/bottom-navigation/bottom-navigation.style.ts
- src/button/button.stories.ts
> feat: add banner components

- src/avatar/avatar.stories.ts
- src/avatar/avatar.style.ts
- src/avatar/avatar.ts
> fix: update avatar styles and stories

- src/segmented-button-group/segmented-button-group.style.ts
> feat: add tokens to segmented-button-group

- src/row/index.ts
- src/row/row.stories.ts
- src/row/row.style.ts
- src/row/row.ts
> feat: Add row component

- src/button/button.style.ts
- src/toast/toast.stories.ts
- src/toast/toast.style.ts
- src/toast/toast.ts
> feat: add tokens to toast component

- src/row/row.stories.ts
- src/row/row.style.ts
- src/row/row.ts
- update row stories
- remove title and subtitle from row component
> fix: remove title and subtitle from `row` component

- custom-elements.json
- pnpm-lock.yaml
- src/stepper/index.ts
- src/stepper/stepper.stories.ts
- src/stepper/stepper.style.ts
- src/stepper/stepper.ts
> feat: add `stepper` component

- custom-elements.json
- src/badge/badge.stories.ts
- src/badge/badge.style.ts
- src/badge/badge.ts
- src/badge/index.ts
- src/badge/types.ts
> docs: add JSDoc to ‍‍`badge` component

- src/toast/index.ts
- src/toast/toast.stories.ts
- src/toast/toast.style.ts
- src/toast/toast.ts
> docs: add JSDoc to `toast` component 

- src/step-indicator/index.ts
- src/step-indicator/step-indicator.stories.ts
- src/step-indicator/step-indicator.style.ts
- src/step-indicator/step-indicator.ts
> docs: add JSDoc to `step-indicator` component

- src/pinwheel/index.ts
- src/pinwheel/pinwheel.stories.ts
- src/pinwheel/pinwheel.style.ts
- src/pinwheel/pinwheel.ts
- src/progress-indicator/index.ts
- src/progress-indicator/progress-indicator.stories.ts
- src/progress-indicator/progress-indicator.style.ts
- src/progress-indicator/progress-indicator.ts
> docs: add JSDoc to`progress-indicator` component

- src/modal/index.ts
- src/modal/modal.stories.ts
- src/modal/modal.style.ts
- src/modal/modal.ts
> docs: add JSDoc to `modal` component

- src/checkbox/checkbox.stories.ts
- src/checkbox/checkbox.style.ts
- src/checkbox/checkbox.ts
- src/checkbox/index.ts
> docs: add JSDoc to `checkbox` component

- src/bottom-navigation-item/bottom-navigation-item.style.ts
- src/bottom-navigation-item/bottom-navigation-item.ts
- src/bottom-navigation-item/index.ts
- src/bottom-navigation/bottom-navigation.stories.ts
- src/bottom-navigation/bottom-navigation.style.ts
- src/bottom-navigation/bottom-navigation.ts
- src/bottom-navigation/index.ts
> docs: add JSDoc to `bottom-navigation` and `bottom-navigation-item` component

- src/stepper/index.ts
- src/text-field/index.ts
- src/text-field/text-field.stories.ts
- src/text-field/text-field.style.ts
- src/text-field/text-field.ts
> docs: add JSDoc to `text-field` component

- src/radio-group/index.ts
- src/radio-group/radio-group.stories.ts
- src/radio-group/radio-group.style.ts
- src/radio-group/radio-group.ts
- src/radio/index.ts
- src/radio/radio.stories.ts
- src/radio/radio.style.ts
- src/radio/radio.ts
> docs: add JSDoc to `radio` component 

- src/spinner/index.ts
- src/spinner/spinner.stories.ts
- src/spinner/spinner.style.ts
- src/spinner/spinner.ts
close: https://github.com/Tap30/web-components/issues/29
> feat: add ‍‍‍`spinner‍‍`

- src/base-button/base-button.ts
- src/button/button.test.ts
I think we should write test for our components based on these scenarios:
* Default Behavior
* Property and Attribute Changes
* User Interactions
* Conditional Rendering
* Slot Content
* Events
* Accessibility
> test: add tests of button component

- src/button/index.ts
- src/icon-button/index.ts
> docs: add button demo

- docs/components/[component].md
- src/switch/index.ts
- src/switch/switch.stories.ts
- src/switch/switch.style.ts
- src/switch/switch.ts
> feat: add `Switch` component

- docs/.vitepress/config.ts
- docs/dev/components/elements-config.json
- package.json
- packages/theme/src/tokens/spacing.css
- packages/web-components/src/chip-group/chip-group.style.ts
- packages/web-components/src/chip-group/chip-group.ts
- packages/web-components/src/chip-group/index.ts
- packages/web-components/src/chip/chip.style.ts
- packages/web-components/src/chip/chip.ts
- packages/web-components/src/chip/constants.ts
- packages/web-components/src/chip/index.ts
- packages/web-components/src/utils/index.ts
- packages/web-components/src/utils/repaint.ts
> fix(chips): resolve `disabled` and `full-width` behavior

- docs/dev/components/elements-config.json
- packages/web-components/src/input/constants.ts
- packages/web-components/src/input/input.style.ts
- packages/web-components/src/input/input.ts
- packages/web-components/src/text-field/constants.ts
- packages/web-components/src/text-field/index.ts
- packages/web-components/src/text-field/text-field.style.ts
- packages/web-components/src/text-field/text-field.ts
- packages/web-components/src/textarea/index.ts
- packages/web-components/src/textarea/textarea.style.ts
- packages/web-components/src/textarea/textarea.ts
- packages/web-components/src/utils/dom/get.ts
> fix: resolve `autofocus` and design inconsistencies of TextArea and TextField

- docs/dev/components/elements-config.json
- packages/web-components/src/badge-wrapper/badge-wrapper.style.ts
- packages/web-components/src/badge-wrapper/badge-wrapper.ts
- packages/web-components/src/badge-wrapper/constants.ts
- packages/web-components/src/badge-wrapper/index.ts
- packages/web-components/src/badge/badge.style.ts
- packages/web-components/src/badge/badge.ts
- packages/web-components/src/badge/constants.ts
- packages/web-components/src/badge/index.ts
- packages/web-components/src/badge/types.ts
- pnpm-lock.yaml
resolves: #241 
resolves: #240
> refactor(badge): update variants and their corresponding styles

- packages/web-components/src/button/base/base-button.style.ts
- packages/web-components/src/modal/modal.style.ts
- packages/web-components/src/rate-slider/rate-slider.style.ts
- packages/web-components/src/skeleton/skeleton.style.ts
- packages/web-components/src/spinner/spinner.style.ts
- packages/web-components/src/switch/switch.style.ts
> feat(accessibility): reduce motions

- packages/web-components/src/radio/radio.style.ts
- packages/web-components/src/radio/radio.ts
closes: #304 
https://github.com/user-attachments/assets/92b78745-5d48-429a-9d02-a7d561456a17
> feat(radio): update component ui for checked state

- packages/web-components/src/checkbox/checkbox.style.ts
- packages/web-components/src/checkbox/checkbox.ts
closes: #305 
https://github.com/user-attachments/assets/734276e6-9e96-4e19-99cd-aac704e2cf79
> feat(checkbox): add transition

- .changeset/stupid-rings-rush.md
- docs/icons.md
- packages/web-icons/scripts/build.ts
- packages/web-icons/templates/web-icon.txt
> fix(web-icons): convert importing path to kebab-case

- .changeset/fresh-experts-lie.md
- packages/web-components/src/discount-card/discount-card.style.ts
- packages/web-components/src/discount-card/discount-card.ts
> fix: resolve discount card growing body issue
